---
name: NoAdvertisings
version: 0.0.4
api:
- 4.0.0
main: YTBJero\NoAdvertisings\Main
author: YTBJero
website: github.com/JeroGamingYT

commands:
  noadvertisings:
    aliases:
    - noads
    - na
    description: NoAdvertisings Control
    usage: /noadvertisings
    permission: noadvertisings.blocked

permissions:
  noadvertisings.blocked:
    description: NoAdvertisings Control
    default: op
...
